CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "email" varchar,
  "address" varchar,
  "city" varchar,
  "image_url" varchar
);

CREATE TABLE "employee" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user" int,
  "role" varchar
);

CREATE TABLE "passwords" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user" int,
  "password" varchar
);

CREATE TABLE "product" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "password" varchar,
  "stock" int,
  "unit_price" numeric,
  "unit_measure" varchar,
  "category" int,
  "total_purchases" int,
  "date_expiration" Date,
  "image_url" varchar
);

CREATE TABLE "category" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar
);

CREATE TABLE "invoice" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user" int,
  "delivery_commission" numeric,
  "total" numeric,
  "date" Date
);

CREATE TABLE "invoice_detail" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "invoice" int,
  "product" int,
  "quantity" int
);

CREATE TABLE "delivery" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "is_delivered" boolean,
  "employee" int,
  "invoice" int,
  "date" Date
);

ALTER TABLE "users" ADD FOREIGN KEY ("id") REFERENCES "employee" ("user");

ALTER TABLE "passwords" ADD FOREIGN KEY ("user") REFERENCES "users" ("id");

ALTER TABLE "users" ADD FOREIGN KEY ("id") REFERENCES "invoice" ("user");

ALTER TABLE "product" ADD FOREIGN KEY ("id") REFERENCES "invoice_detail" ("product");

ALTER TABLE "employee" ADD FOREIGN KEY ("id") REFERENCES "delivery" ("employee");

ALTER TABLE "invoice" ADD FOREIGN KEY ("id") REFERENCES "delivery" ("invoice");

ALTER TABLE "invoice_detail" ADD FOREIGN KEY ("invoice") REFERENCES "invoice" ("id");

ALTER TABLE "product" ADD FOREIGN KEY ("category") REFERENCES "category" ("id");
